name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build APK with Buildozer Action
        uses: subito-it/buildozer-action@v1
        with:
          command: buildozer -v android debug
          buildozer_version: master

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SilverQuant-APK
          path: bin/*.apk
